index:
    path: /{_locale}
    controller: App\Controller\DefaultController::index
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'
contact:
    path: /{_locale}/contact
    controller: App\Controller\DefaultController::contact
    requirements:
        _locale: '%app.supported_locales%'
boutique:
    path: /{_locale}/boutique
    controller: App\Controller\BoutiqueController::index
    requirements:
        _locale: '%app.supported_locales%'
panier:
    path: /{_locale}/panier
    controller: App\Controller\PanierController::index
    requirements:
        _locale: '%app.supported_locales%'
panier_ajouter:
    path: /{_locale}/panier/ajouter/{idProduit}/{quantite}
    controller: App\Controller\PanierController::ajouter
    requirements:
        _locale: '%app.supported_locales%'
panier_enlever:
    path: /{_locale}/panier/enlever/{idProduit}/{quantite}
    controller: App\Controller\PanierController::enlever
    requirements:
        _locale: '%app.supported_locales%'
panier_supprimer:
    path: /{_locale}/panier/supprimer/{idProduit}
    controller: App\Controller\PanierController::supprimer
    requirements:
        _locale: '%app.supported_locales%'
panier_vider:
    path: /{_locale}/panier/vider
    controller: App\Controller\PanierController::vider
    requirements:
        _locale: '%app.supported_locales%'
rayon:
    path: /{_locale}/boutique/rayon/{idCategorie}
    controller: App\Controller\BoutiqueController::rayon
    requirements:
        _locale: '%app.supported_locales%'
search:
    path: /{_locale}/boutique/chercher
    controller: App\Controller\BoutiqueController::searchAction
    requirements:
        _locale: '%app.supported_locales%'
